// AUTO-GENERATED by AMC segment-compose — do not edit.
import type { NextRequest, NextResponse } from "next/server";
export type MiddlewareHook = (req: NextRequest) => NextResponse | null | void | Promise<NextResponse | null | void>;
import { localHooks } from './hooks.local';
export const generatedHooks: MiddlewareHook[] = [];
export { localHooks };
export const allMiddlewareHooks: MiddlewareHook[] = [...generatedHooks, ...localHooks];
