// AUTO-GENERATED by AMC segment-compose — do not edit.
// Auth pack not composed — null session control.
import type { ReactNode } from "react";
export function SiteHeaderAuth(_props: { cookieSignedIn?: boolean }): ReactNode {
  return null;
}
