// AUTO-GENERATED by AMC segment-compose — do not edit.
// Nav only lists routes that the composed segments actually ship.
export type SiteNavLink = { href: string; label: string };
export const siteCapabilities = {
  "hasPricing": false,
  "hasAuth": false,
  "hasBilling": false,
  "hasDashboard": false,
  "hasPlay": false,
  "links": []
} as const;
export const siteNavLinks: SiteNavLink[] = siteCapabilities.links as unknown as SiteNavLink[];
