// AUTO-GENERATED by AMC segment-compose — do not edit.
import type { ReactNode } from "react";
import { localProviders } from "./registry.local";
const generatedProviders = [] as Array<(p: { children: ReactNode }) => ReactNode>;
export { localProviders };
export function GeneratedProviders({ children }: { children: ReactNode }) {
  const chain = [...generatedProviders, ...localProviders];
  return chain.reduceRight(
    (acc, Prov) => <Prov>{acc}</Prov>,
    children as ReactNode
  );
}
